# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

#gem "ezframe", path: "../../../work/ezframe"
gem "ezframe", ">= 0.4.0"
