extra_js_list: 
  - https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js
extra_css_list: 
  - https://fonts.googleapis.com/icon?family=Material+Icons
  - https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css
